
logging.config: http://192.168.1.189:8888/${spring.application.name}/development/master/logback.xml

metadata:
  config: ${boku.cloud.config.uri}/${spring.application.name}/development/master/metadata.json
